name: mlMiniProj
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.2.0=h9c3ff4c_2
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dbus=1.13.6=h48d8840_2
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.4.0=h6987444_5
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.28.1=py39h3811e60_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2021.10.1=pyhd3eb1b0_0
  - future=0.18.2=py39hf3d152e_4
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h7b6447c_0
  - glib=2.70.1=h780b84a_0
  - glib-tools=2.70.1=h780b84a_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.5=hf529b03_2
  - gstreamer=1.18.5=h9f60fe5_2
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=68.2=h9c3ff4c_0
  - imagecodecs=2021.8.26=py39h4cda21f_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9d=h7f8727e_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h0b77cf5_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.70.1=h174f98d_0
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.46.0=hce63b2e_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.1=py39hf3c14e0_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hbc83047_0
  - libpq=13.5=hd57d9b9_0
  - libprotobuf=3.18.1=h780b84a_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - locket=0.2.1=py39h06a4308_1
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.0=py39hf3d152e_0
  - matplotlib-base=3.5.0=py39h2fa2bec_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7f8727e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.10.2=h4bd325d_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.72=hb5efdd6_0
  - numpy=1.21.4=py39hdbf815f_0
  - olefile=0.46=pyhd3eb1b0_0
  - opencv=4.5.1=py39hf3d152e_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.1=py39hef51801_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=cpu_py39hc5866cc_0
  - pywavelets=1.1.1=py39h6323ea4_4
  - pyyaml=6.0=py39h7f8727e_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - scikit-image=0.18.3=py39h51133e4_0
  - scipy=1.7.1=py39h292c36d_2
  - setuptools=59.1.1=py39hf3d152e_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.36.0=h9cd32fc_2
  - tbb=2021.4.0=h4bd325d_1
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.11.1=py39_cu113
  - tornado=6.1=py39h3811e60_2
  - typing_extensions=4.0.0=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h4bd325d_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h2531618_6
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=haebb681_0
